"""Update column names

Revision ID: 7bfeb7f96b4e
Revises: 433b4b8e4b09
Create Date: 2024-02-22 14:26:09.616133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bfeb7f96b4e'
down_revision = '433b4b8e4b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.drop_column('date_of_expense')
        batch_op.drop_column('title_of_expense')
        batch_op.drop_column('amout_of_expense')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amout_of_expense', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('title_of_expense', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('date_of_expense', sa.DATE(), nullable=False))
        batch_op.drop_column('date')
        batch_op.drop_column('amount')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
